# Clean up the stale issues

daysUntilStale: 30
daysUntilClose: 1

exemptLabels:
  - in progress
  - pending

staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

closeComment: false
